// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package sik.client.admin.services;

public final class RMIClient_Stub
    extends java.rmi.server.RemoteStub
    implements java.rmi.Remote
{
    private static final long serialVersionUID = 2;
    
    // constructors
    public RMIClient_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
}
